SELECT 
     Q1.SABOR
    ,Q1.ANO
    ,FORMAT( Q1.FATURAMENTO, 'C', 'pt-br' ) AS FATURAMENTO
    ,FORMAT( Q1.FATURAMENTO / Q2.TOTAL , 'P' )  AS PARTICIPACAO
FROM
    (
        SELECT --TOP 10 
            PROD.SABOR
            ,YEAR( NF.[DATA] ) AS ANO
            ,SUM( INF.QUANTIDADE * INF.PREÇO )  AS FATURAMENTO
        FROM [ITENS NOTAS FISCAIS] INF
        LEFT JOIN 
            [TABELA DE PRODUTOS] PROD ON INF.[CODIGO DO PRODUTO] = PROD.[CODIGO DO PRODUTO]
        INNER JOIN 
            [NOTAS FISCAIS] NF ON INF.NUMERO = NF.NUMERO
        WHERE YEAR(NF.[DATA]) = 2016
        GROUP BY 
            PROD.SABOR
            ,YEAR( NF.[DATA] )
    ) Q1
    INNER JOIN 
        (
        SELECT --TOP 10 
            YEAR( NF.[DATA] ) AS ANO
            ,SUM( INF.QUANTIDADE * INF.PREÇO )  AS TOTAL
        FROM [ITENS NOTAS FISCAIS] INF
        LEFT JOIN 
            [TABELA DE PRODUTOS] PROD ON INF.[CODIGO DO PRODUTO] = PROD.[CODIGO DO PRODUTO]
        INNER JOIN 
            [NOTAS FISCAIS] NF ON INF.NUMERO = NF.NUMERO
        WHERE YEAR(NF.[DATA]) = 2016
        GROUP BY 
            YEAR( NF.[DATA] )

        ) Q2
    ON Q1.ANO = Q2.ANO
    ORDER BY Q1.FATURAMENTO DESC